export const reducerMethods = {
  setAdultCount: "SET_ADULTCOUNT",
  setChildCount: "SET_CHILDCOUNT",
  setRoomsCount: "SET_ROOMS_COUNT",
  setSelectedRooms: "SET_SELECTED_ROOMS",
  setTotalPrice: "SET_TOTAL_PRICE",
  setIsOfferAvailable: "SET_IS_OFFER_AVAILABLE",
  setOffers: "SET_OFFERS",
  setShouldShowCallback: "SET_SHOULD_SHOW_CALLBACK",
  setGuestOptions: "SET_GUEST_OPTIONS", // sets adults,children and rooms count
  setGuestDetails: "SET_GUEST_DETAILS",
  setCheckInDate: "SET_CHECK_IN_DATE",
  setCheckOutDate: "SET_CHECK_OUT_DATE",
  setIsHomePage: "SET_IS_HOME_PAGE",
  setSelectedRoomTypeId: "SET_SELECTED_ROOM_TYPE_ID",
  setSteppersActiveStep: "SET_STEPPERS_ACTIVE_STEP",
  setIsUserLoggedIn: "SET_IS_USER_LOGGED_IN",
  setLoggedInUser: "SET_LOGGED_IN_USER",
  setAllRoomTypes: "SET_ALL_ROOM_TYPES",
  setFilteredAllRoomTypes: "SET_FILTERED_ALL_ROOM_TYPES",
  setUserDetailsForPayment: "SET_USER_DETAILS_FOR_PAYMENT",
  setAllRoomTypesName: "SET_ALL_ROOM_TYPES_NAMES",
  setAllAssetsImages: "SET_ALL_ASSETS_IMAGES",
};
