export const reducerMethods = {
  setLoginData: "SET_LOGINDATA",
  setLogInDataErr: "SET_LOGINDATA_ERR",
  setSignUpData: "SET_SIGNUPDATA",
  setSignUpdataErr: "SET_SIGNUPDATA_ERR",
  setReqCallbackData: "SET_REQ_CALLBACK_DATA",
  setReqCallbackDataErr: "SET_REQCALLBACK_DATAERR",
  setShowHam: "SET_SHOWHAM",
  setMenuOpen: "SET_MENU_OPEN",
  setSize: "SET_SIZE",
  setOpen: "SET_OPEN",
  setColorchange: "SET_COLORCHANGE",
  setRevertHeader: "SET_REVERT_HEADER",
  setAdultCount: "SET_ADULTCOUNT",
  setChildCount: "SET_CHILDCOUNT",
  setRoomsCount: "SET_ROOMS_COUNT",
  setSelectedRooms: "SET_SELECTED_ROOMS",
  setTotalPrice: "SET_TOTAL_PRICE",
  setShouldShowCallback: "SET_SHOULD_SHOW_CALLBACK",
  setGuestOptions: "SET_GUEST_OPTIONS", // sets adults,children and rooms count
  setCheckInDate: "SET_CHECK_IN_DATE",
  setCheckOutDate: "SET_CHECK_OUT_DATE",
  setIsHomePage: "SET_IS_HOME_PAGE",
  setSelectedRoomTypeId: "SET_SELECTED_ROOM_TYPE_ID",
  setSteppersActiveStep: "SET_STEPPERS_ACTIVE_STEP",
  setAllRoomTypes: "SET_ALL_ROOM_TYPES",
};
